In [ ]:
import numpy as np

In [ ]:
# Unidimensional
array_one_dim = np.array([1, 2, 3, 4, 5])

In [ ]:
# Obter elemento na posição 0
print(array_one_dim[0])

1


In [ ]:
# Obter elemento na posição 0
print(array_one_dim[0:3])

[1 2 3]


In [ ]:
array_two_dim = np.array([[ 0,  1,  2,  3,  4],
                          [ 5,  6,  7,  8,  9],
                          [10, 11, 12, 13, 14]])

In [ ]:
print(array_two_dim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Obter elemento na linha 1 e coluna 1
print(array_two_dim[1,1])

6

In [ ]:
## Obter dimensoes
print("Tamanho array unidimensional: ", array_one_dim.shape)
print("Tamanho array bidimensional: ", array_two_dim.shape)

Tamanho array unidimensional:  (5,)
Tamanho array bidimensional:  (3, 5)


### Operações

In [ ]:
A = np.array([[1, 1],
              [0, 2]])

B = np.array([[2, 0],
              [3, 4]])

In [ ]:
# Multiplicação de matrizes
A.dot(B)

array([[5, 4],
       [6, 8]])

In [ ]:
# Produto "elemento-a-elemento" (Hadamard)
A * B

array([[2, 0],
       [0, 8]])

In [ ]:
# Adição por escalar
A + 1

array([[2, 2],
       [1, 3]])

In [ ]:
# Multiplicacao por escalar
A * 4

array([[4, 4],
       [0, 8]])

In [ ]:
# Atribuição a partir de condição
A_c = A.copy()
A_c[A_c == 1] = -8

In [ ]:
A_c

array([[-8, -8],
       [ 0,  2]])

In [ ]:
A_c = A.copy()
A_c[A_c < 1] = -8

In [ ]:
A_c

array([[ 1,  1],
       [-8,  2]])